name: cd; Docker Build & Push

on:
  push:
    branches: ["main"]   # build on pushes to main
    tags: ["v*"]         # also build on version tags (e.g. v1.0.0)

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Set up Docker Buildx (for multi-platform builds, caching, etc.)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/iris-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
