# create cicd
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 79 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
      - name: Build Docker image
        run: |
          docker build -t mlflow-test-saturday .
      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name mlflow-test-saturday \
            -e MLFLOW_TRACKING_URI="https://dagshub.com/larawehbe/mlflow-test-saturday.mlflow" \
            -e MLFLOW_TRACKING_USERNAME="$DAGSHUB_USER" \
            -e MLFLOW_TRACKING_PASSWORD="$DAGSHUB_TOKEN" \
            mlflow-test-saturday
      - name: Verify Docker container is running
        run: |
          docker ps | grep mlflow-test-saturday
      - name: Stop and remove Docker container
        run: |
          docker stop mlflow-test-saturday
          docker rm mlflow-test-saturday  